spring.application.name=demo

# Local test için API key kullanmanız gerekirse aşağıdaki yorum satırını açabilirsiniz:
# gemini.api.key=BURAYA_API_KEY

gemini.api.key=${GEMINI_API_KEY:}
gemini.model=gemini-1.5-flash
# H2 Database & JPA Settings
spring.datasource.url=jdbc:h2:file:./data/stockxer-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console